playsbc:
  config:
    sip_ip: 0.0.0.0
    sip_advertised_ip: 172.28.0.20
    b2bua_advertised_ip: 192.168.28.20
    sip_port: 5060
    sip_transport: udp
    rtp_min: 30000
    rtp_max: 30100
    log_dir: /var/log/playsbc
    default_codec: PCMA
    auth_realm: playsbc
    users: {}
    bridge_rooms:
      - bridge
    b2bua_routes:
      peer-b: sip:peer-b@192.168.28.30:5060
    route_policies:
      - name: peer-static-route
        match: peer-b
        target: sip:{user}@192.168.28.30:5060
        priority: 20
    b2bua_ladder_logs: true
    media_backend: rtpengine
    rtpengine_url: udp://172.28.0.40:2223
    rtpengine_timeout: 5.0
    rtpengine_directions:
      - core
      - peer
    rtpengine_interfaces:
      - core
      - peer
    ha:
      enabled: true
      cluster_id: playsbc-aa-lab
      node_id: playsbc-a
      shared_state_path: /var/lib/playsbc/ha-state.sqlite3
      rtpengine_pairs:
        - name: core-pair-a
          node_id: playsbc-a
          rtpengine_url: udp://172.28.0.40:2223
        - name: peer-pair-b
          node_id: playsbc-b
          rtpengine_url: udp://192.168.28.40:2223
    reject_unknown_routes: true
    debug: true
