{{- if and .Values.authSecret.enabled (not .Values.authSecret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "playsbc.fullname" . }}-auth
  labels:
{{ include "playsbc.labels" . | indent 4 }}
type: Opaque
stringData:
  users.yaml: |
    users:
{{ toYaml .Values.authSecret.users | indent 6 }}
{{- end }}
