apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "playsbc.fullname" . }}-config
  labels:
{{ include "playsbc.labels" . | indent 4 }}
data:
  server.yaml: |
{{ toYaml .Values.playsbc.config | indent 4 }}
