apiVersion: v1
kind: Service
metadata:
  name: {{ include "playsbc.fullname" . }}
  labels:
{{ include "playsbc.labels" . | indent 4 }}
{{- if or .Values.observability.prometheus.scrapeAnnotations .Values.service.annotations }}
  annotations:
{{- if .Values.observability.prometheus.scrapeAnnotations }}
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "{{ .Values.service.healthPort }}"
{{- end }}
{{- with .Values.service.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  selector:
    app.kubernetes.io/name: {{ include "playsbc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: sip-udp
      port: {{ .Values.service.sipPort }}
      targetPort: sip-udp
      protocol: UDP
    - name: sip-tcp
      port: {{ .Values.service.sipPort }}
      targetPort: sip-tcp
      protocol: TCP
    - name: sip-tls
      port: {{ .Values.service.tlsPort }}
      targetPort: sip-tls
      protocol: TCP
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
